services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: my-weights-postgres
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/bitnami/postgresql'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my-weights-db

volumes:
  postgres_data:
